plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

javafx {
    version = '21'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

sourceSets {
    main {
        java {
            srcDirs = ['.']
            include 'src/**/*.java'
        }
    }
}

application {
    mainClass = 'src.HelloFX'
}

tasks.register('runCLI', JavaExec) {
    group = 'application'
    description = 'Runs the CLI Chess Game'
    mainClass = 'src.Main'
    classpath = sourceSets.main.runtimeClasspath
    standardInput = System.in
}
